### ISSUE TITLE
aseprite script help

### ISSUE THREAD

**Issue by ghost** [behreajj/AsepriteAddons#2]
Hi

I saw you have a lot of experience writing aseprite scripts.
I have an idea and want to convert it into a aseprite script. But I have too little knowledge of lua and aseprite API.
Maybe you want to help me? The code idea is very simple. I just can't convert it into a script :(

Here you can read everything and look at my C# code: https://github.com/aseprite/aseprite/issues/3291

thank you so much!
PixelArtGirl

**Comment by behreajj** [comment]
Hi @pixelartgirl,

Sounds like a fun idea! Below are the key function where I'd start looking. There's a lot to run through, so I might've missed something. I wrote a [tutorial](https://behreajj.medium.com/how-to-script-aseprite-tools-in-lua-8f849b08733) about a year ago that covers some of the basics. Aseprite has a debugger now -- that's the biggest change to scripting since then, imo.

Cheers,
Jeremy

***

In a script, you can load an [Image](https://github.com/aseprite/api/blob/main/api/image.md#image-1) from a file if you use the constructor that looks like this: `local image = Image { fromFile = filename }`. `filename` would be a `string`. Both Lua and C# allow for [named arguments](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/named-and-optional-arguments). In Lua, a function is called with curly braces when named arguments are used. An equal sign is used instead of a colon.

You don't have to limit yourself to a `.jpg`. But if you leave the format open, you'd have to deal with other complications: a file with multiple frames, multiple layers or with a different color mode than RGB. 

If you want to make a [Dialog](https://github.com/aseprite/api/blob/main/api/dialog.md#dialog), then the user can choose the file path using a [file widget](https://github.com/aseprite/api/blob/main/api/dialog.md#dialogfile). The widget allows you to limit which file formats are allowed once the file browser pops up.

[app.fs](https://github.com/aseprite/api/blob/main/api/app_fs.md) is where Aseprite's file system tools are located. If you want to check that the extension of a file is a `.jpg`, you can do that with [app.fs.fileExtension](https://github.com/aseprite/api/blob/main/api/app_fs.md#appfsfileextension).

To loop over all the pixels in an image, you have two options. The first is to use an [iterator](https://github.com/aseprite/api/blob/main/api/image.md#imagepixels). If you want to store pixels in an array, use the iterator to populate the array.

```lua
local pixelArray = {}
local pixelIterator = image:pixels()
for elm in pixelIterator do
    local hexAbgr = elm() -- Getting
    elm(hexAbgr) -- Setting
    table.insert(pixelArray, hexAbgr)
end
```
Lua arrays begin at `1` and go to `#table` (the table's length). This is different than C#, which starts at `0` and goes to `table.Length - 1`.

The second option is to use [Image:getPixel](https://github.com/aseprite/api/blob/main/api/image.md#imagegetpixel) and [Image:drawPixel](https://github.com/aseprite/api/blob/main/api/image.md#imagedrawpixel). These functions make more sense if you want to use nested for-loops.

```lua
local width = image.width
local height = image.height
for y = 0, height - 1, 1 do
    for x = 0, width - 1, 1 do
        image:drawPixel(x, y, image:getPixel(x, y))
    end
end
```

You can convert a 1D index to 2D coordinates with `x = index % width` and `y = index // height`. You can convert 2D coordinates to a 1D index with `index = width * y + x`. Again, the wrinkle that I left out of these formulas is that Lua arrays start at `1`, not `0`.

For the summing and averaging, use [app.pixelColor](https://github.com/aseprite/api/blob/main/api/pixelcolor.md#apppixelcolor) to break down the color from an ABGR 32 bit integer into its component channels.

```lua
local rAvg = 0
local gAvg = 0
local bAvg = 0
for elm in image:pixels() do
    local hexAbgr = elm()
    local r = app.pixelColor.rgbaR(hexAbgr)
    local g = app.pixelColor.rgbaG(hexAbgr)
    local b = app.pixelColor.rgbaB(hexAbgr)

    -- There is no += shorthand in Lua.
    rAvg = rAvg + r
    gAvg = gAvg + g
    bAvg = bAvg + b
end

local flatLen = image.width * image.height
rAvg = rAvg / flatLen
gAvg = gAvg / flatLen
bAvg = bAvg / flatLen
```
New colors can be composed with [app.pixelColor.rgba](https://github.com/aseprite/api/blob/main/api/pixelcolor.md#apppixelcolorrgba).

For randomness, have a look at `math.random` in the [Lua documentation](https://www.lua.org/manual/5.4/manual.html#pdf-math.random).

You'd have to get creative to draw, say, a 5x5 rectangle of color onto an image. You could create a little image that is [cleared](https://github.com/aseprite/api/blob/main/api/image.md#imageclear) to one color, then use [Image:drawImage](https://github.com/aseprite/api/blob/main/api/image.md#imagedrawimage). The _destination_ image calls the method, the _source_ image is supplied as an argument.

An image can be saved with [Image:saveAs](https://github.com/aseprite/api/blob/main/api/image.md#imagesaveas).

**Comment by pixelartgirl** [comment]
Thx a lot!!!
I'm now trying to understand everything, because i'm new to aseprite, lua and aseprite api :-D

Can I ask questions here if I'm stuck or can we communicate by email? (because this is not an issue for your scripts :) )

If I can ask things by email, let me know and I write my email here.

**Comment by pixelartgirl** [comment]
Is there a main() function in Lua or do I just put all lines somewhere and they run from top of the file to the end?

**Comment by pixelart-girl** [comment]
Hello

As you can see I deleted my account.
It's too hard for me to make this. I'm an autistic girl and it's hard to learn new things for me.

Is it possible you make it for me?
I'm used to C# but can't make the switch to lua and this aseprite things.

Thanks
PixelArtGirl

**Comment by behreajj** [comment]
Hi @pixelart-girl,

Oh ok, I was confused by the deleted account. That's why I closed the thread. Eh, I would just give it some time and take small steps. Switching between programming languages is _always_ overwhelming. Even if you decide Lua's not worthwhile, being able to write apps in C# is still plenty cool.

**Comment by pixelart-girl** [comment]
FUCK YOU MOTHERFUCKER
